---
apiVersion: v1
kind: Service
metadata:
  name: ltc-node
  labels:
    app: ltc-node
spec:
  ports:
  - port: 9333
    name: port
  - port: 9332
    name: rpc
  selector:
    app: ltc-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ltc-node
spec:
  selector:
    matchLabels:
      app: ltc-node
  serviceName: ltc-node
  replicas: 5
  updateStrategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ltc-node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ltc-node
        image: vicsufer/ltc:0.18.2
        ports:
        - containerPort: 9333
          name: port
        - containerPort: 9332
          name: rpc
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        readinessProbe:
          tcpSocket:
            port: 9333
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9333
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: blockchain-data
          mountPath: /opt/blockchain/data
        - name: litecoin-config
          mountPath: "/opt/blockchain/config/litecoin.conf"
          subPath: "litecoin.conf"
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
        - name: litecoin-config
          configMap:
            name: configmap-ltc-node
  volumeClaimTemplates:
  - metadata:
      name: blockchain-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"  # On cloud we must use AWSElasticBlockStore, AzureDisk, or any other provider.
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ltc-node
data: 
# This configuration is the same as the one in the Dockerfile, any tweeks to config should be done here never in the image
#   in order to avoid rebuilding the image just for a configuration change.
  litecoin.conf: |
    datadir=/opt/blockchain/data
    dbcache=256
    maxmempool=512
    port=9333
    rpcport=9332
    listen=1
    server=1
    maxconnections=16
    logtimestamps=1
    logips=1
    rpcallowip=127.0.0.1
    rpctimeout=15
    rpcclienttimeout=15
